# We use alpine for a lightweight (less memory) image
FROM node

# Create app directory
WORKDIR /app

# Copy the files that declares the dependencies (in this case using yarn)
COPY package.json ./

# Check if all the files are correct when building
RUN ls -a

# Install the dependencies
RUN npm install

# Copy all the files into the container to run the app
COPY . .

EXPOSE 3000:3000
# Run command to start the process runing a shell command using node
CMD ["npm", "start"]
